language: python
python:
  - "3.7"
install:
  #- pip install -e .
  - pip install -r requirements.txt
  - pip install pytest-cov codecov # Install packages for code coverage report
  - pip install -e .
script:
  - pytest tests
after_success:
  - codecov