language: python
python:
-"3.7"
install:
- pip install -e .
- pip install pytest-cov codecov # Install packages for code coverage report
script:
- pytest tests
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)